<?php
declare(strict_types=1);

return [
    'library' => [
        'name' => 'vanilla-cookieconsent',
        'version' => '3.1.0',
    ],
    'revision' => 3,
    'material_version' => '2026-08-12.2',
    'retention_days' => 1095,
    'cookie' => [
        'name' => 'kk_consent',
        'expires_after_days' => 182,
    ],
    'mtm' => [
        // Öffentliche Container-ID, kein Zugangstoken. Der Container wird
        // ausschließlich nach Einwilligung in den Provider Matomo geladen.
        'container' => '1ZzpGfcK',
    ],
    'categories' => [
        'necessary' => [
            'label' => 'Notwendig',
            'description' => 'Erforderlich für grundlegende Funktionen und deine Datenschutzeinstellungen.',
            'read_only' => true,
        ],
        'analytics' => [
            'label' => 'Analyse',
            'description' => 'Hilft uns zu verstehen, welche Inhalte und Planungshilfen genutzt werden.',
            'read_only' => false,
        ],
        'functional' => [
            'label' => 'Externe Funktionen',
            'description' => 'Lädt externe Inhalte nur, wenn du sie wirklich nutzen möchtest.',
            'read_only' => false,
        ],
        'marketing' => [
            'label' => 'Marketing',
            'description' => 'Misst den Erfolg unserer Werbung. Du kannst jeden Anbieter einzeln auswählen.',
            'read_only' => false,
        ],
    ],
    'providers' => [
        'matomo' => [
            'category' => 'analytics',
            'managed_by' => 'mtm',
            'name' => 'Matomo',
            'purpose' => 'Reichweitenmessung und Verbesserung der Website.',
            'data' => 'Seitenaufrufe, Interaktionen, gekürzte technische Nutzungsdaten.',
            'recipient' => 'Klas Küchen; technische Verarbeitung über die selbst gehostete Matomo-Instanz.',
            'privacy_url' => '/datenschutz/',
            'third_country' => 'Keine planmäßige Drittlandübermittlung.',
            'storage' => 'First-Party-Cookies nach Einwilligung.',
            'retention' => 'Gemäß der in Matomo hinterlegten Löschfrist.',
            'cookies' => ['/^_pk_/', 'mtm_consent', 'mtm_cookie_consent'],
        ],
        'google_maps' => [
            'category' => 'functional',
            'managed_by' => 'component',
            'name' => 'Google Maps',
            'purpose' => 'Zeigt den Standort und erleichtert die Anfahrtsplanung.',
            'data' => 'IP-Adresse, aufgerufene Seite und technisch erforderliche Verbindungsdaten; abhängig von deinen Google-Einstellungen weitere Nutzungsdaten.',
            'recipient' => 'Google Ireland Limited und verbundene Google-Unternehmen.',
            'privacy_url' => '/datenschutz/',
            'third_country' => 'Eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums kann nicht ausgeschlossen werden.',
            'storage' => 'Google kann Cookies oder vergleichbare Browser-Speicher verwenden.',
            'retention' => 'Die Speicherdauer richtet sich nach Dienst, Google-Konto und deinen Google-Einstellungen.',
            'cookies' => [],
        ],
        'google_ads' => [
            'category' => 'marketing',
            'managed_by' => 'mtm',
            'name' => 'Google Ads',
            'purpose' => 'Messung von Anzeigenaufrufen und erfolgreichen Kontakt- oder Terminabschlüssen.',
            'data' => 'Seitenaufrufe, Interaktionen, Kampagnen- und technische Nutzungsdaten.',
            'recipient' => 'Google Ireland Limited und verbundene Google-Unternehmen.',
            'privacy_url' => '/datenschutz/',
            'third_country' => 'Eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums kann nicht ausgeschlossen werden.',
            'storage' => 'Cookies und vergleichbare Browser-Speicher nach Einwilligung.',
            'retention' => 'Gemäß den Einstellungen des eingesetzten Google-Ads-Dienstes.',
            'cookies' => ['/^_gcl_/', '/^_ga/', 'IDE', 'test_cookie'],
        ],
        'meta' => [
            'category' => 'marketing',
            'managed_by' => 'mtm',
            'name' => 'Meta Pixel',
            'purpose' => 'Messung von Anzeigenaufrufen und erfolgreichen Kontakt- oder Terminabschlüssen.',
            'data' => 'Seitenaufrufe, Interaktionen, Kampagnen- und technische Nutzungsdaten.',
            'recipient' => 'Meta Platforms Ireland Limited und verbundene Meta-Unternehmen.',
            'privacy_url' => '/datenschutz/',
            'third_country' => 'Eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums kann nicht ausgeschlossen werden.',
            'storage' => 'Cookies und vergleichbare Browser-Speicher nach Einwilligung.',
            'retention' => 'Gemäß den Einstellungen des eingesetzten Meta-Dienstes.',
            'cookies' => ['_fbp', '_fbc'],
        ],
        'microsoft_ads' => [
            'category' => 'marketing',
            'managed_by' => 'mtm',
            'name' => 'Microsoft Advertising',
            'purpose' => 'Messung von Anzeigenaufrufen und erfolgreichen Kontakt- oder Terminabschlüssen.',
            'data' => 'Seitenaufrufe, Interaktionen, Kampagnen- und technische Nutzungsdaten.',
            'recipient' => 'Microsoft Ireland Operations Limited und verbundene Microsoft-Unternehmen.',
            'privacy_url' => '/datenschutz/',
            'third_country' => 'Eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums kann nicht ausgeschlossen werden.',
            'storage' => 'Cookies und vergleichbare Browser-Speicher nach Einwilligung.',
            'retention' => 'Gemäß den Einstellungen des eingesetzten Microsoft-Advertising-Dienstes.',
            'cookies' => ['_uetmsclkid', '_uetsid', '_uetvid', 'MUID'],
        ],
        'pinterest' => [
            'category' => 'marketing',
            'managed_by' => 'mtm',
            'name' => 'Pinterest Tag',
            'purpose' => 'Messung von Anzeigenaufrufen und erfolgreichen Kontakt- oder Terminabschlüssen.',
            'data' => 'Seitenaufrufe, Interaktionen, Kampagnen- und technische Nutzungsdaten.',
            'recipient' => 'Pinterest Europe Ltd. und verbundene Pinterest-Unternehmen.',
            'privacy_url' => '/datenschutz/',
            'third_country' => 'Eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums kann nicht ausgeschlossen werden.',
            'storage' => 'Cookies und vergleichbare Browser-Speicher nach Einwilligung.',
            'retention' => 'Gemäß den Einstellungen des eingesetzten Pinterest-Dienstes.',
            'cookies' => ['_pin_unauth', '_pinterest_ct_ua'],
        ],
    ],
];
